/**
 * VRF Callback Service
 *
 * Handles Chainlink VRF fulfillment callbacks.
 * Processes random number and triggers winner selection.
 */

import { raffleRepo } from '@/lib/db/repositories';
import * as raffleDrawService from '../raffle/raffle-draw.service';
import { VRFRequestError } from '../errors';
import { getVRFRequestStatus } from './contract-read.service';

/**
 * Process VRF fulfillment callback
 *
 * Called by Chainlink when random number is ready.
 * Triggers winner selection for the raffle.
 *
 * @param requestId VRF request ID from Chainlink
 * @param randomNumber Random number generated by VRF
 *
 * @throws VRFRequestError if verification fails
 */
export async function handleVRFFulfillment(
  requestId: string,
  randomNumber: bigint,
  chainId: number = 137
): Promise<void> {
  // Verify request on-chain
  const vrfStatus = await getVRFRequestStatus(requestId, chainId);

  if (!vrfStatus.fulfilled) {
    throw new VRFRequestError('VRF request not fulfilled on-chain');
  }

  if (vrfStatus.randomNumber !== randomNumber) {
    throw new VRFRequestError('Random number mismatch');
  }

  // Find raffle with this VRF request ID
  const raffle = await findRaffleByVRFRequest(requestId);

  if (!raffle) {
    throw new VRFRequestError(`No raffle found for VRF request: ${requestId}`);
  }

  // Verify raffle is in drawing status
  if (raffle.status !== 'drawing') {
    throw new VRFRequestError(
      `Raffle ${raffle.raffleId} is not in drawing status (current: ${raffle.status})`
    );
  }

  // Complete the draw using the random number
  await raffleDrawService.completeRaffleDraw(raffle.raffleId, randomNumber);
}

/**
 * Verify VRF callback authenticity
 *
 * Validates that the callback came from Chainlink VRF coordinator
 *
 * @param requestId VRF request ID
 * @param signature Callback signature
 * @returns true if valid, false otherwise
 */
export function verifyVRFCallback(requestId: string, signature: string): boolean {
  // TODO: Implement signature verification
  // Should verify that callback came from Chainlink VRF coordinator
  // using ECDSA signature validation

  // For now, basic validation
  if (!requestId || requestId.length === 0) {
    return false;
  }

  if (!signature || signature.length === 0) {
    return false;
  }

  // In production, verify signature against VRF coordinator address
  return true;
}

/**
 * Find raffle by VRF request ID
 *
 * Scans drawing raffles to find one with matching VRF request
 */
async function findRaffleByVRFRequest(requestId: string) {
  // Get all raffles in drawing status
  const result = await raffleRepo.getByStatus('drawing');
  const drawingRaffles = result.items;

  // Find raffle with matching VRF request ID
  return drawingRaffles.find((r) => r.vrfRequestId === requestId) || null;
}
