AWSTemplateFormatVersion: '2010-09-09'
Description: >
  FairWin Production Environment - DynamoDB Tables
  Deploys shared tables (Users, PlatformStats) and Raffle game-specific tables for production with enhanced settings

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
    Description: Environment name

Resources:
  # ===========================================
  # SHARED TABLES (Cross-Game)
  # ===========================================

  # Users Table - Shared across all games
  # Primary Key: walletAddress (HASH)
  #
  # Stores aggregate user statistics across ALL games on the platform.
  # No GSIs needed - only accessed by wallet address (primary key).
  # ===========================================
  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'FairWin-${Environment}-Users'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: walletAddress
          AttributeType: S
      KeySchema:
        - AttributeName: walletAddress
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: FairWin
        - Key: ManagedBy
          Value: CloudFormation
        - Key: TableType
          Value: Shared
        - Key: CriticalData
          Value: 'true'

  # ===========================================
  # RAFFLE GAME TABLES
  # ===========================================

  # Raffle-Raffles Table
  # Primary Key: raffleId (HASH)
  # GSI1: status-endTime-index (status as HASH, endTime as RANGE)
  # GSI2: type-createdAt-index (type as HASH, createdAt as RANGE)
  #
  # Access Patterns:
  # 1. Get raffle by ID → Primary key query
  # 2. Get raffles by status (active, scheduled, completed, etc.) → GSI1
  # 3. Get raffles by type (daily, weekly, monthly, flash, mega) → GSI2
  #
  # The endTime range on GSI1 allows sorting by draw time (useful for "ending soon" lists)
  # The createdAt range on GSI2 allows chronological sorting (newest first)
  # ===========================================
  RaffleRafflesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'FairWin-${Environment}-Raffle-Raffles'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: raffleId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: endTime
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: raffleId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-endTime-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: endTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: type-createdAt-index
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: FairWin
        - Key: ManagedBy
          Value: CloudFormation
        - Key: GameType
          Value: Raffle
        - Key: CriticalData
          Value: 'true'

  # ===========================================
  # Raffle-Entries Table
  # Primary Key: entryId (HASH)
  # GSI1: raffleId-createdAt-index (raffleId as HASH, createdAt as RANGE)
  # GSI2: walletAddress-createdAt-index (walletAddress as HASH, createdAt as RANGE)
  #
  # Access Patterns:
  # 1. Get entry by ID → Primary key query
  # 2. Get all entries for a raffle → GSI1 (for winner selection, refunds, participant list)
  # 3. Get all entries by a user → GSI2 (for user entry history)
  #
  # GSI1 is critical for winner selection (need all entries for a raffle)
  # GSI2 enables user profile showing their entry history across all raffles
  # CreatedAt as range key allows chronological ordering (most recent first)
  # ===========================================
  RaffleEntriesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'FairWin-${Environment}-Raffle-Entries'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: entryId
          AttributeType: S
        - AttributeName: raffleId
          AttributeType: S
        - AttributeName: walletAddress
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: entryId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: raffleId-createdAt-index
          KeySchema:
            - AttributeName: raffleId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: walletAddress-createdAt-index
          KeySchema:
            - AttributeName: walletAddress
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: FairWin
        - Key: ManagedBy
          Value: CloudFormation
        - Key: GameType
          Value: Raffle
        - Key: CriticalData
          Value: 'true'

  # ===========================================
  # Raffle-Winners Table
  # Primary Key: winnerId (HASH)
  # GSI1: raffleId-createdAt-index (raffleId as HASH, createdAt as RANGE)
  # GSI2: walletAddress-createdAt-index (walletAddress as HASH, createdAt as RANGE)
  #
  # Access Patterns:
  # 1. Get winner by ID → Primary key query
  # 2. Get all winners for a raffle → GSI1 (for displaying raffle results)
  # 3. Get all wins by a user → GSI2 (for user win history, profile)
  #
  # Payout information is stored directly in winner records:
  # - payoutStatus (pending, processing, paid, failed)
  # - payoutTransactionHash (transaction hash when paid)
  # - payoutProcessedAt (timestamp when paid)
  # - payoutError (error message if failed)
  #
  # No separate Payouts table needed - simplified architecture.
  # ===========================================
  RaffleWinnersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'FairWin-${Environment}-Raffle-Winners'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: winnerId
          AttributeType: S
        - AttributeName: raffleId
          AttributeType: S
        - AttributeName: walletAddress
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: winnerId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: raffleId-createdAt-index
          KeySchema:
            - AttributeName: raffleId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: walletAddress-createdAt-index
          KeySchema:
            - AttributeName: walletAddress
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: FairWin
        - Key: ManagedBy
          Value: CloudFormation
        - Key: GameType
          Value: Raffle
        - Key: CriticalData
          Value: 'true'

Outputs:
  # ===== SHARED TABLES =====

  UsersTableName:
    Description: Users table name (Shared across all games)
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${Environment}-UsersTableName'

  UsersTableArn:
    Description: Users table ARN
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub '${Environment}-UsersTableArn'

  # ===== RAFFLE GAME TABLES =====

  RaffleRafflesTableName:
    Description: Raffle-Raffles table name (stores raffle configurations and state)
    Value: !Ref RaffleRafflesTable
    Export:
      Name: !Sub '${Environment}-RaffleRafflesTableName'

  RaffleRafflesTableArn:
    Description: Raffle-Raffles table ARN
    Value: !GetAtt RaffleRafflesTable.Arn
    Export:
      Name: !Sub '${Environment}-RaffleRafflesTableArn'

  RaffleEntriesTableName:
    Description: Raffle-Entries table name (stores user raffle entries/tickets)
    Value: !Ref RaffleEntriesTable
    Export:
      Name: !Sub '${Environment}-RaffleEntriesTableName'

  RaffleEntriesTableArn:
    Description: Raffle-Entries table ARN
    Value: !GetAtt RaffleEntriesTable.Arn
    Export:
      Name: !Sub '${Environment}-RaffleEntriesTableArn'

  RaffleWinnersTableName:
    Description: Raffle-Winners table name (stores winners and payout information)
    Value: !Ref RaffleWinnersTable
    Export:
      Name: !Sub '${Environment}-RaffleWinnersTableName'

  RaffleWinnersTableArn:
    Description: Raffle-Winners table ARN
    Value: !GetAtt RaffleWinnersTable.Arn
    Export:
      Name: !Sub '${Environment}-RaffleWinnersTableArn'
