AWSTemplateFormatVersion: '2010-09-09'
Description: >
  MassiveHike Stage Environment - DynamoDB Tables
  Deploys Users table for staging/development environment
  Region: ap-south-1 (Mumbai)

Parameters:
  Environment:
    Type: String
    Default: Stage
    AllowedValues:
      - Stage
    Description: Environment name

Resources:
  # ===========================================
  # Users Table
  # Primary Key: userId (HASH)
  # GSI1: email-index (email as HASH) - for authentication lookup
  # GSI2: referralCode-index (referralCode as HASH) - for referral link validation
  # ===========================================
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'MassiveHike-${Environment}-Users'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: referralCode
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        # Email index for authentication and user lookup by email
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        # Referral code index for validating referral links
        - IndexName: referralCode-index
          KeySchema:
            - AttributeName: referralCode
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: MassiveHike
        - Key: ManagedBy
          Value: SAM

  # ===========================================
  # StakeConfigs Table
  # Primary Key: stakeConfigId (HASH)
  # Contains staking plan configurations (duration, rates, limits)
  # Read-only in application - managed via console
  # ===========================================
  StakeConfigsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'MassiveHike-${Environment}-StakeConfigs'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: stakeConfigId
          AttributeType: S
      KeySchema:
        - AttributeName: stakeConfigId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: MassiveHike
        - Key: ManagedBy
          Value: SAM

  # ===========================================
  # ReferralConfigs Table
  # Primary Key: referralConfigId (HASH)
  # Contains referral commission structure (rates per level, max levels)
  # Read-only in application - managed via console
  # ===========================================
  ReferralConfigsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'MassiveHike-${Environment}-ReferralConfigs'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: referralConfigId
          AttributeType: S
      KeySchema:
        - AttributeName: referralConfigId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: MassiveHike
        - Key: ManagedBy
          Value: SAM

  # ===========================================
  # Stakes Table
  # Primary Key: stakeId (HASH)
  # GSI1: userId-index (userId as HASH, createdAt as RANGE) - for user's stakes history
  # GSI2: status-index (status as HASH, createdAt as RANGE) - for admin to view pending/verifying stakes
  # GSI3: txHash-index (txHash as HASH) - for blockchain verification lookup
  # ===========================================
  StakesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'MassiveHike-${Environment}-Stakes'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: stakeId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: txHash
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: stakeId
          KeyType: HASH
      GlobalSecondaryIndexes:
        # User stakes index - get all stakes for a user sorted by date
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # Status index - admin view of stakes by status (pending, verifying, etc.)
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # TxHash index - lookup stake by blockchain transaction hash
        - IndexName: txHash-index
          KeySchema:
            - AttributeName: txHash
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: MassiveHike
        - Key: ManagedBy
          Value: SAM

Outputs:
  UsersTableName:
    Description: Users table name
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${Environment}-MassiveHike-UsersTableName'

  UsersTableArn:
    Description: Users table ARN
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub '${Environment}-MassiveHike-UsersTableArn'

  EmailIndexName:
    Description: Email GSI name
    Value: email-index
    Export:
      Name: !Sub '${Environment}-MassiveHike-EmailIndexName'

  ReferralCodeIndexName:
    Description: Referral Code GSI name
    Value: referralCode-index
    Export:
      Name: !Sub '${Environment}-MassiveHike-ReferralCodeIndexName'

  StakeConfigsTableName:
    Description: StakeConfigs table name
    Value: !Ref StakeConfigsTable
    Export:
      Name: !Sub '${Environment}-MassiveHike-StakeConfigsTableName'

  StakeConfigsTableArn:
    Description: StakeConfigs table ARN
    Value: !GetAtt StakeConfigsTable.Arn
    Export:
      Name: !Sub '${Environment}-MassiveHike-StakeConfigsTableArn'

  ReferralConfigsTableName:
    Description: ReferralConfigs table name
    Value: !Ref ReferralConfigsTable
    Export:
      Name: !Sub '${Environment}-MassiveHike-ReferralConfigsTableName'

  ReferralConfigsTableArn:
    Description: ReferralConfigs table ARN
    Value: !GetAtt ReferralConfigsTable.Arn
    Export:
      Name: !Sub '${Environment}-MassiveHike-ReferralConfigsTableArn'

  StakesTableName:
    Description: Stakes table name
    Value: !Ref StakesTable
    Export:
      Name: !Sub '${Environment}-MassiveHike-StakesTableName'

  StakesTableArn:
    Description: Stakes table ARN
    Value: !GetAtt StakesTable.Arn
    Export:
      Name: !Sub '${Environment}-MassiveHike-StakesTableArn'

  UserIdIndexName:
    Description: UserId GSI name
    Value: userId-index
    Export:
      Name: !Sub '${Environment}-MassiveHike-UserIdIndexName'

  StatusIndexName:
    Description: Status GSI name
    Value: status-index
    Export:
      Name: !Sub '${Environment}-MassiveHike-StatusIndexName'

  TxHashIndexName:
    Description: TxHash GSI name
    Value: txHash-index
    Export:
      Name: !Sub '${Environment}-MassiveHike-TxHashIndexName'


#!/bin/bash
# aws cloudformation deploy \
#   --template-file infra/dynamo/stage.yaml \
#   --stack-name massivehike-stage-dynamo \
#   --region ap-south-1